# 谷歌地图英文国家
google_country_dict = {'afghanistan': 'Afghanistan', 'åland islands': 'Åland Islands', 'albania': 'Albania',
                       'algeria': 'Algeria', 'american samoa': 'American Samoa', 'andorra': 'Andorra',
                       'angola': 'Angola', 'anguilla': 'Anguilla', 'antarctica': 'Antarctica',
                       'antigua and barbuda': 'Antigua and Barbuda', 'argentina': 'Argentina', 'armenia': 'Armenia',
                       'aruba': 'Aruba', 'australia': 'Australia', 'austria': 'Austria', 'azerbaijan': 'Azerbaijan',
                       'bahamas': 'The Bahamas', 'bahrain': 'Bahrain', 'bangladesh': 'Bangladesh',
                       'barbados': 'Barbados', 'belarus': 'Belarus', 'belgium': 'Belgium', 'belize': 'Belize',
                       'benin': 'Benin', 'bermuda': 'Bermuda', 'bhutan': 'Bhutan', 'bolivia': 'Bolivia',
                       'bonaire, sint eustatius and saba (netherlands)': 'Sint Eustatius',
                       'bosnia and herzegovina': 'Bosnia and Herzegovina', 'botswana': 'Botswana',
                       'bouvet island': 'Bouvet Island', 'brazil': 'Brazil',
                       'british indian ocean territory': 'British Indian Ocean Territory',
                       'brunei darussalam': 'Brunei', 'brunei': 'Brunei', 'bulgaria': 'Bulgaria',
                       'burkina faso': 'Burkina Faso', 'burundi': 'Burundi', 'cape verde': 'Cape Verde',
                       'cambodia': 'Cambodia', 'cameroon': 'Cameroon', 'canada': 'Canada',
                       'cayman islands': 'Cayman Islands', 'central african': 'Central African Republic',
                       'central african republic': 'Central African Republic', 'chad': 'Chad', 'chile': 'Chile',
                       'china': 'China', 'christmas island': 'Christmas Island', 'colombia': 'Colombia',
                       'comoros': 'Comoros', 'democratic republic of congo': 'Democratic Republic of the Congo',
                       'congo dr': 'Democratic Republic of the Congo', 'congo': 'Democratic Republic of the Congo',
                       'cook islands': 'Cook Islands', 'costa rica': 'Costa Rica', 'croatia': 'Croatia', 'cuba': 'Cuba',
                       'curaçao': 'Curaçao', 'cyprus': 'Cyprus', 'czech republic': 'Czechia', 'denmark': 'Denmark',
                       'djibouti': 'Djibouti', 'dominica': 'Dominica', 'dominican rep': 'Dominican Republic',
                       'dominican republic': 'Dominican Republic', 'ecuador': 'Ecuador', 'egypt': 'Egypt',
                       'el salvador': 'El Salvador', 'equatorial guinea': 'Equatorial Guinea', 'eritrea': 'Eritrea',
                       'estonia': 'Estonia', 'ethiopia': 'Ethiopia',
                       'falkland islands  [malvinas]': 'Falkland Islands (Islas Malvinas)',
                       'faroe islands (denmark)': 'Faroe Islands', 'fiji': 'Fiji', 'finland': 'Finland',
                       'france': 'France', 'french guiana (france)': 'French Guiana',
                       'french polynesia (france)': 'French Polynesia',
                       'french southern territories': 'French Southern and Antarctic Lands', 'gabon': 'Gabon',
                       'gambia': 'The Gambia', 'georgia': 'Georgia', 'germany': 'Germany', 'ghana': 'Ghana',
                       'gibraltar': 'Gibraltar', 'greece': 'Greece', 'greenland (denmark)': 'Greenland',
                       'grenada': 'Grenada', 'guadeloupe (france)': 'Guadeloupe',
                       'guam (united states of america)': 'Guam', 'guatemala': 'Guatemala',
                       'guernsey (united kingdom)': 'Guernsey', 'guinea': 'Guinea', 'guinea bissau': 'Guinea-Bissau',
                       'guyana': 'Guyana', 'haiti': 'Haiti',
                       'heard island and mcdonald islands': 'Heard Island and McDonald Islands',
                       'holy see': 'Vatican City', 'honduras': 'Honduras', 'hong kong': 'Hong Kong',
                       'hungary': 'Hungary', 'iceland': 'Iceland', 'india': 'India', 'indonesia': 'Indonesia',
                       'islamic republic of iran': 'Iran', 'iraq': 'Iraq', 'ireland': 'Ireland',
                       'isle of man (united kingdom)': 'Isle of Man', 'israel': 'Israel', 'italy': 'Italy',
                       'jamaica': 'Jamaica', 'japan': 'Japan', 'jersey (united kingdom)': 'Jersey', 'jordan': 'Jordan',
                       'kazakhstan': 'Kazakhstan', 'kenya': 'Kenya', 'kiribati': 'Kiribati',
                       'democratic peoples republic of korea': 'North Korea', 'republic of korea': 'South Korea',
                       'kuwait': 'Kuwait', 'kyrgyzstan': 'Kyrgyzstan', 'latvia': 'Latvia', 'lebanon': 'Lebanon',
                       'lesotho': 'Lesotho', 'liberia': 'Liberia', 'libya': 'Libya', 'liechtenstein': 'Liechtenstein',
                       'lithuania': 'Lithuania', 'luxembourg': 'Luxembourg', 'macao': 'Macao',
                       'macedonia': 'North Macedonia', 'macedonia (fyrom)': 'North Macedonia',
                       'madagascar': 'Madagascar', 'malawi': 'Malawi', 'malaysia': 'Malaysia', 'maldives': 'Maldives',
                       'mali': 'Mali', 'malta': 'Malta', 'marshall islands': 'Marshall Islands',
                       'martinique': 'Martinique', 'martinique (france)': 'Martinique', 'mauritania': 'Mauritania',
                       'mauritius': 'Mauritius', 'mayotte (france)': 'Mayotte', 'mexico': 'Mexico',
                       'republic of moldova': 'Moldova', 'monaco': 'Monaco', 'mongolia': 'Mongolia',
                       'montenegro': 'Montenegro', 'montserrat': 'Montserrat', 'morocco': 'Morocco',
                       'mozambique': 'Mozambique', 'myanmar/burma': 'Myanmar (Burma)', 'namibia': 'Namibia',
                       'nauru': 'Nauru', 'nepal': 'Nepal', 'netherlands': 'Netherlands',
                       'new caledonia (france)': 'New Caledonia', 'new zealand': 'New Zealand',
                       'nicaragua': 'Nicaragua', 'niger': 'Niger', 'nigeria': 'Nigeria', 'niue': 'Niue',
                       'norfolk island': 'Norfolk Island', 'northern mariana islands': 'Northern Mariana Islands',
                       'norway': 'Norway', 'oman': 'Oman', 'pakistan': 'Pakistan', 'palau': 'Palau',
                       'palestinian territories': 'Palestine', 'panama': 'Panama',
                       'papua new guinea': 'Papua New Guinea', 'paraguay': 'Paraguay', 'peru': 'Peru',
                       'philippines': 'Philippines', 'pitcairn': 'Pitcairn Islands', 'poland': 'Poland',
                       'portugal': 'Portugal', 'puerto rico': 'Puerto Rico',
                       'puerto rico (united states of america)': 'Puerto Rico', 'reunion (france)': 'Réunion',
                       'romania': 'Romania', 'russian federation': 'Russia', 'rwanda': 'Rwanda',
                       'saint helena, ascension and tristan da cunha': 'St Helena, Ascension and Tristan da Cunha',
                       'saint kitts and nevis': 'St Kitts & Nevis', 'saint lucia': 'St Lucia',
                       'saint martin (france)': 'St Martin', 'saint pierre and miquelon': 'St Pierre and Miquelon',
                       'saint vincent and the grenadines': 'St Vincent and the Grenadines', 'samoa': 'Samoa',
                       'san marino': 'San Marino', 'sao tome and principe': 'São Tomé and Príncipe',
                       'saudi arabia': 'Saudi Arabia', 'senegal': 'Senegal', 'serbia': 'Serbia',
                       'seychelles': 'Seychelles', 'sierra leone': 'Sierra Leone', 'singapore': 'Singapore',
                       'sint maarten': 'Sint Maarten', 'slovakia': 'Slovakia', 'slovenia': 'Slovenia',
                       'solomon islands': 'Solomon Islands', 'somalia': 'Somalia', 'south africa': 'South Africa',
                       'south georgia and the south sandwich islands': 'South Georgia and the South Sandwich Islands',
                       'south sudan': 'South Sudan', 'spain': 'Spain', 'sri lanka': 'Sri Lanka', 'sudan': 'Sudan',
                       'suriname': 'Suriname', 'svalbard and jan mayen': 'Svalbard and Jan Mayen',
                       'swaziland': 'Eswatini', 'sweden': 'Sweden', 'switzerland': 'Switzerland',
                       'syrian arab republic': 'Syria', 'taiwan': 'Taiwan', 'tajikistan': 'Tajikistan',
                       'united republic of tanzania': 'Tanzania', 'thailand': 'Thailand', 'timor-leste': 'Timor-Leste',
                       'togo': 'Togo', 'tokelau': 'Tokelau', 'tonga': 'Tonga',
                       'trinidad and tobago': 'Trinidad and Tobago', 'tunisia': 'Tunisia', 'turkey': 'Turkey',
                       'turkmenistan': 'Turkmenistan', 'turks and caicos islands': 'Turks and Caicos Islands',
                       'tuvalu': 'Tuvalu', 'uganda': 'Uganda', 'ukraine': 'Ukraine',
                       'united arab emirates': 'United Arab Emirates', 'united kingdom': 'United Kingdom',
                       'united states minor outlying islands': 'United States Minor Outlying Islands',
                       'united states of america': 'United States', 'uruguay': 'Uruguay', 'uzbekistan': 'Uzbekistan',
                       'vanuatu': 'Vanuatu', 'venezuela': 'Venezuela', 'vietnam': 'Vietnam',
                       'virgin islands (british)': 'British Virgin Islands',
                       'virgin islands (united states of america)': 'U.S. Virgin Islands',
                       'wallis and futuna': 'Wallis and Futuna', 'western sahara*': 'Western Sahara', 'yemen': 'Yemen',
                       'zambia': 'Zambia', 'zimbabwe': 'Zimbabwe', 'lao peoples democratic republic': 'Laos',
                       'cote divoire': "Côte d'Ivoire", 'kosovo': 'Kosovo'}
# 国家缩写后缀
country_suffix_dict = {
    'af': 'Afghanistan', 'fk': 'land Islands', 'al': 'Albania', 'dz': 'Algeria',
    'as': 'American Samoa', 'ad': 'Andorra', 'ao': 'Angola', 'ai': 'Anguilla', 'aq': 'Antarctica',
    'ag': 'Antigua and Barbuda', 'ar': 'Argentina', 'am': 'Armenia', 'aw': 'Aruba',
    'au': 'Australia', 'at': 'Austria', 'az': 'Azerbaijan', 'bs': 'Bahamas', 'bh': 'Bahrain',
    'bd': 'Bangladesh', 'bb': 'Barbados', 'by': 'Belarus', 'be': 'Belgium', 'bz': 'Belize',
    'bj': 'Benin', 'bm': 'Bermuda', 'bt': 'Bhutan', 'ga': 'Bolivia', 'ba': 'Bosnia and Herzegovina',
    'bw': 'Botswana', 'bv': 'Bouvet Island', 'br': 'Brazil', 'io': 'British Indian Ocean Territory',
    'bn': 'Brunei Darussalam', 'bg': 'Bulgaria', 'bf': 'Burkina Faso', 'bi': 'Burundi',
    'cv': 'Cape Verde', 'kh': 'Cambodia', 'cm': 'Cameroon', 'ca': 'Canada', 'ky': 'Cayman Islands',
    'cf': 'Central African Republic', 'td': 'Chad', 'cl': 'Chile', 'cn': 'China',
    'cx': 'Christmas Island', 'cc': 'Cocos', 'co': 'Colombia', 'km': 'Comoros', 'cg': 'Congo',
    'ck': 'Cook Islands', 'cr': 'Costa Rica', 'hr': 'Croatia', 'cu': 'Cuba', 'cy': 'Cyprus',
    'cz': 'Czech Republic', 'dk': 'Denmark', 'dj': 'Djibouti', 'do': 'Dominica', 'ec': 'Ecuador',
    'eg': 'Egypt', 'sv': 'El Salvador', 'cq': 'Equatorial Guinea', 'ee': 'Estonia', 'et': 'Ethiopia',
    'fo': 'Faroe Islands (Denmark)', 'fj': 'Fiji', 'fi': 'Finland', 'fr': 'France',
    'gf': 'French Guiana (France)', 'pf': 'French Polynesia (France)',
    'tf': 'French Southern Territories', 'gm': 'Gambia', 'ge': 'Georgia', 'de': 'Germany',
    'gh': 'Ghana', 'gi': 'Gibraltar', 'vi': 'Greece', 'gl': 'Grenada', 'gp': 'Guadeloupe (France)',
    'gt': 'Guatemala', 'gn': 'Guinea', 'gw': 'Guinea Bissau', 'gy': 'Guyana', 'ht': 'Haiti',
    'hm': 'Heard Island and McDonald Islands', 'va': 'Holy See', 'hn': 'Honduras', 'hk': 'Hong Kong',
    'hu': 'Hungary', 'is': 'Iceland', 'in': 'India', 'id': 'Indonesia',
    'ir': 'Islamic Republic of Iran', 'iq': 'Iraq', 'ie': 'Ireland', 'il': 'Israel', 'it': 'Italy',
    'jm': 'Jamaica', 'jp': 'Japan', 'jo': 'Jordan', 'kz': 'Kazakhstan', 'ke': 'Kenya',
    'ki': 'Kiribati', 'kp': 'Democratic Peoples Republic of Korea', 'kr': 'Republic of Korea',
    'kw': 'Kuwait', 'kg': 'Kyrgyzstan', 'lv': 'Latvia', 'lb': 'Lebanon', 'ls': 'Lesotho',
    'lr': 'Liberia', 'ly': 'Libya', 'li': 'Liechtenstein', 'lt': 'Lithuania', 'lu': 'Luxembourg',
    'mo': 'Macao', 'mg': 'Madagascar', 'mw': 'Malawi', 'my': 'Malaysia', 'mv': 'Maldives',
    'ml': 'Mali', 'mt': 'Malta', 'mh': 'Marshall Islands', 'mq': 'Martinique (France)',
    'mr': 'Mauritania', 'mx': 'Mexico', 'fm': 'Micronesia', 'md': 'Republic of Moldova',
    'mc': 'Monaco', 'mn': 'Mongolia', 'ms': 'Montserrat', 'ma': 'Morocco', 'mz': 'Mozambique',
    'mm': 'Myanmar/Burma', 'na': 'Namibia', 'nr': 'Nauru', 'np': 'Nepal', 'nl': 'Netherlands',
    'nc': 'New Caledonia (France)', 'nz': 'New Zealand', 'ni': 'Nicaragua', 'ne': 'Niger',
    'ng': 'Nigeria', 'nu': 'Niue', 'nf': 'Norfolk Island', 'mp': 'Northern Mariana Islands',
    'no': 'Norway', 'om': 'Oman', 'pk': 'Pakistan', 'pw': 'Palau', 'pa': 'Panama',
    'pg': 'Papua New Guinea', 'py': 'Paraguay', 'pe': 'Peru', 'ph': 'Philippines', 'pn': 'Pitcairn',
    'pl': 'Poland', 'pt': 'Portugal', 'qa': 'Qatar', 're': 'Reunion (France)', 'ro': 'Romania',
    'ru': 'Russian Federation', 'rw': 'Rwanda', 'kn': 'Saint Kitts and Nevis', 'sh': 'Saint Lucia',
    'pm': 'Saint Pierre and Miquelon', 'vc': 'Saint Vincent and the Grenadines', 'sm': 'San Marino',
    'st': 'Sao Tome and Principe', 'sa': 'Saudi Arabia', 'sn': 'Senegal', 'sc': 'Seychelles',
    'sl': 'Sierra Leone', 'sg': 'Singapore', 'sk': 'Slovakia', 'si': 'Slovenia',
    'sb': 'Solomon Islands', 'so': 'Somalia', 'za': 'South Africa', 'ss': 'South Sudan',
    'es': 'Spain', 'lk': 'Sri Lanka', 'sd': 'Sudan', 'sr': 'Suriname', 'sz': 'Swaziland',
    'se': 'Sweden', 'ch': 'Switzerland', 'sy': 'Syrian Arab Republic', 'tw': 'Taiwan',
    'tj': 'Tajikistan', 'tz': 'United Republic of Tanzania', 'th': 'Thailand', 'tl': 'Timor-Leste',
    'tg': 'Togo', 'tk': 'Tokelau', 'to': 'Tonga', 'tt': 'Trinidad and Tobago', 'tn': 'Tunisia',
    'tr': 'Turkey', 'tm': 'Turkmenistan', 'tc': 'Turks and Caicos Islands', 'tv': 'Tuvalu',
    'ug': 'Uganda', 'ua': 'Ukraine', 'ae': 'United Arab Emirates', 'uk': 'United Kingdom',
    'pr': 'United States Minor Outlying Islands', 'us': 'United States of America', 'uy': 'Uruguay',
    'vu': 'Vanuatu', 've': 'Venezuela', 'vn': 'VietNam', 'vg': 'Virgin Islands (British)',
    'wf': 'Wallis and Futuna', 'ws': 'Western Sahara*', 'ye': 'Yemen', 'zm': 'Zambia',
    'zw': 'Zimbabwe', 'la': 'Lao Peoples Democratic Republic', 'ci': 'COTE DIVOIRE'}
